services:
  database:
    container_name: database
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    networks:
      web-interna:
        ipv4_address: 10.0.0.2
    volumes:
      - db_data:/var/lib/mysql
      - db_scripts:/docker-entrypoint-initdb.d/
    tmpfs:
      - /var/run/mysqld      
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
  api_laravel:
    container_name: api_laravel
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      web-interna:
        ipv4_address: 10.0.0.3
    volumes:
      - api_php:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
  api_node:
    container_name: api_node
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    ports:
      - "443:8443"
    restart: always
    command: npm run start:dev
    networks:
      web-interna:
        ipv4_address: 10.0.0.4
    volumes:
      - api_node:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    restart: always
    command: npm run start:https
    networks:
      web-interna:
        ipv4_address: 10.0.0.5
    volumes:
      - front:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
networks:
  web-interna:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./mysql/data
      o: bind
  db_scripts:
    driver: local
    driver_opts:
      type: none
      device: ./mysql/scripts
      o: bind
  api_php:
    driver: local
    driver_opts:
      type: none
      device: ./php
      o: bind
  api_node:
    driver: local
    driver_opts:
      type: none
      device: ./node
      o: bind
  front:
    driver: local
    driver_opts:
      type: none
      device: ./front
      o: bind