FROM node:22.18 AS builder
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /app
RUN apt-get update && apt-get install -y \
  build-essential \
  python3 \
  make \
  g++
COPY . .
RUN npm install -g node-gyp
RUN npm install
ENV CHOKIDAR_USEPOLLING=true
