FROM node:20 AS builder
ENV TZ=America/Sao_Paulo
WORKDIR /app
COPY . .
RUN npm install
COPY exemple.env .env
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV TZ=America/Sao_Paulo
